### ISSUE TITLE
usage on Apple Mail

### ISSUE THREAD

**Issue by alessandromenini** [bitrockteam/signature#2]
The company image at the end of the signature has two main issues:
- white background - it would be better to have a transparent background

![schermata 2018-10-04 alle 11 19 30](https://user-images.githubusercontent.com/42537124/46465647-729c4d00-c7c9-11e8-8a89-6db0013e9b7a.png)

- doesn't show when pasting the signature on Mail app (plus the typography seems to be slightly lighter and different)

![schermata 2018-10-04 alle 11 37 44](https://user-images.githubusercontent.com/42537124/46465823-f0605880-c7c9-11e8-9d53-d4fd743fe04b.png)

**Comment by moebiusmania** [comment]
basically are Apple's Mail client limitations, need to check this one https://www.cultofmac.com/305096/create-html-signature-apple-mail/ and eventually add link / quick how to.
